### ISSUE TITLE
Invalid hyperlink to go2.cisco.com

### ISSUE THREAD

**Issue by davemcdonnell** [CiscoDevNet/ucsm_health_check#4]
go2.cisco.com doesnt exist in DNS

**Comment by AkashMalla1** [comment]
Hi, Thank you for reaching out. Looking into this.

**Comment by AkashMalla1** [comment]
Hi, go2 links are the shortened links for long URLs, and I validated all go2 links in the script and all are working. Please let us know the exact issue you are facing with go2 links?

**Comment by riaanvn** [comment]
I have the same issue. I was unable to access any of the go2.cisco.com links

http://go2.cisco.com/UCSBackup
http://go2.cisco.com/UCSCentral
http://go2.cisco.com/power+control+policy
http://go2.cisco.com/RN3-2
http://go2.cisco.com/RN-4

Checking from macOS, it seems the DNS entry does not exist as per the original report:

$ host go2.cisco.com
Host go2.cisco.com not found: 3(NXDOMAIN)

I have tried multiple systems (Windows, macOS, iOS) via multiple internet connections (work, connection, personal wifi & mobile).

Can this please be re-opened or reviewed? Why not just link to the direct pages on the Cisco page instead of depending on redirects?

**Comment by AkashMalla1** [comment]
Hello Riaan, Thank you for reaching out. Let me get this checked internally.

**Comment by AkashMalla1** [comment]
This has been fixed.
